---
- hosts: localhost
  tasks:
    - name: Create a bridge network
      copy:
        src: files/ifcfg-virbr0
        dest: /etc/sysconfig/network-scripts/
        mode: 0664

    - name: Check if the bridging module is loaded
      command: modinfo bridge
      register: load_value

    - name: Load the module if its not already loaded
      command: modprobe --first-time bridge
      when: load_value.rc == 1

#    - name: Install LXC files
#      yum: name={{ item }} state=present update_cache=yes
#      with_items:
#        - lxc
#        - lxc-templates
#        - libcap-devel
#        - libcgroup
#        - wget
#        - bridge-utils
#        - yum
#        - python-lxc

    - name: Check the interface name
      shell: "nmcli |head -1 |cut -d: -f1"
      register: interface_name

    - name: Add network bridge info to above interface
      lineinfile:
        path: /etc/sysconfig/network-scripts/ifcfg-{{ interface_name.stdout }}
        line: BRIDGE=virbr0

    - name: Restart network
      service:
        name: network
        state: restarted
      


#    - name: Disabling default bridge lxcbr0
#      lineinfile:
#        path: /etc/default/lxc-net
#        regexp: '^USE_LXC_BRIDGE='
#        line: USE_LXC_BRIDGE="false"

#    - name: Change the default LXC bridge to br0
#      lineinfile:
#        path: /etc/lxc/default.conf
#        regexp: '^lxc.network.link='
#        line: lxc.network.link=br0

#    - include_tasks: lxc-create.yml
#    - include_tasks: web.yml
